version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fintracker_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongP@ssw0rd!2026
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - fintracker_network

  fintracker-api:
    container_name: fintracker_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=FinTrackerDb;User Id=sa;Password=StrongP@ssw0rd!2026;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    networks:
      - fintracker_network

volumes:
  sqlserver_data:

networks:
  fintracker_network:
    driver: bridge
