name: FinTracker CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore FinTracker.sln

    - name: Build
      run: dotnet build FinTracker.sln --no-restore -c Release

    - name: Test
      run: dotnet test FinTracker.sln --no-build -c Release --verbosity normal
